/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Speech Synthesizer
 #	author : miyako
 #	2017/06/12
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONMAC
#include <AppKit/AppKit.h>
#else
#include <sapi.h>
#include <sphelper.h>  
#endif

#include "cJSON.h"

// --- Speech
void VOICES_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void SAY(sLONG_PTR *pResult, PackagePtr pParams);
