/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Speech-Synthesizer.h
 #	source generated by 4D Plugin Wizard
 #	Project : Speech Synthesizer
 #	author : miyako
 #	2025/03/24
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SPEECH_SYNTHESIZER_H
#define PLUGIN_SPEECH_SYNTHESIZER_H

#include "4DPluginAPI.h"

#if VERSIONMAC
#include <AppKit/AppKit.h>
#else
#include <sapi.h>
#include <sphelper.h>
#endif

#include <map>

#include "ARRAY_TEXT.h"
#include "C_TEXT.h"
#include "4DPlugin-JSON.h"

#pragma mark -

void VOICES_LIST(PA_PluginParameters params);
void SAY(PA_PluginParameters params);

#if VERSIONMAC
static bool isProcessOnExit();
static void onExit();
static void onCloseProcess();
#endif

#if VERSIONWIN
static BOOL GetVoiceId(char *voiceNameStr, CUTF16String &voiceId);
#endif

#endif /* PLUGIN_SPEECH_SYNTHESIZER_H */
