/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Speech Synthesizer
 #	author : miyako
 #	2017/05/30
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#if VERSIONMAC

#pragma mark ctx ref

#pragma mark NSSpeechSynthesizerDelegate


@interface SpeechSynthesizerDelegate : NSObject <NSSpeechSynthesizerDelegate>
{
	uint32_t indx;
	NSSpeechSynthesizer *speechSynthesizer;
}

- (id)initWithVoice:(NSString *)voice volume:(float)volume rate:(float)rate url:(NSURL *)url text:(NSString *)text;

- (void)speechSynthesizer:(NSSpeechSynthesizer *)sender didFinishSpeaking:(BOOL)success;

- (void)abort;

- (BOOL)isSpeaking;

@end

namespace speech
{
	//flag to prevent creating instances after OnExit
	BOOL isDying = NO;

	std::map<uint32_t, SpeechSynthesizerDelegate*> speech_contexts;
	
	uint32_t speech_context_add(SpeechSynthesizerDelegate *speech)
	{
		uint32_t i = 1;
		
		while (speech_contexts.find(i) != speech_contexts.end()) i++;
		
		speech_contexts.insert(std::map<uint32_t, SpeechSynthesizerDelegate*>::value_type(i, speech));
		
		//	NSLog(@"add%i", i);
		
		return i;
	}
	
	void speech_context_remove(uint32_t i)
	{
		std::map<uint32_t, SpeechSynthesizerDelegate*>::iterator pos = speech_contexts.find(i);
		
		if(pos != speech_contexts.end())
		{
			speech_contexts.erase(pos);
			
			//		NSLog(@"remove%i", i);
		}
	}
	
}

@implementation SpeechSynthesizerDelegate

- (id)initWithVoice:(NSString *)voice volume:(float)volume rate:(float)rate url:(NSURL *)url text:(NSString *)text
{
	self = [super init];
	
	if (self)
	{
		speechSynthesizer = [[NSSpeechSynthesizer alloc]initWithVoice:voice];
		
		if(speechSynthesizer)
		{
			indx = speech::speech_context_add(self);
			
			[speechSynthesizer setVolume:volume];
			[speechSynthesizer setRate:rate];
			[speechSynthesizer setDelegate:self];
			
			if(url)
			{
				[speechSynthesizer startSpeakingString:text toURL:url];
			}else
			{
				[speechSynthesizer startSpeakingString:text];
			}
			
		}
	}
	
	return self;
}

- (void)abort
{
	if(speechSynthesizer)
	{
		[speechSynthesizer setDelegate:nil];
		[speechSynthesizer release];
		speechSynthesizer = nil;
	}

	[super dealloc];
}

- (void)speechSynthesizer:(NSSpeechSynthesizer *)sender didFinishSpeaking:(BOOL)success
{
	speech::speech_context_remove(indx);
	
	[self abort];
}

- (BOOL)isSpeaking
{
	if(!speechSynthesizer) return NO;
	
	return [speechSynthesizer isSpeaking];
}

@end

typedef struct
{
	NSString *text;
	NSURL *url;
	float rate;
	float volume;
	NSString *voice;
}say_ctx;

void say(say_ctx *ctx)
{
	if(!speech::isDying)
	{
		
		NSString *voice = nil;
		
		if(ctx->voice)
		{
			NSArray *voices = [NSSpeechSynthesizer availableVoices];
			NSUInteger i = [voices indexOfObjectPassingTest:^BOOL(id obj, NSUInteger idx, BOOL *stop)
											{
												if ([(NSString *)obj isEqualToString:ctx->voice])
												{
													return YES;
												}
												return NO;
											}];
			
			if(NSNotFound != i)
			{
				voice = [voices objectAtIndex:i];
			}
		}
		
		[[SpeechSynthesizerDelegate alloc]initWithVoice:voice
																						 volume:ctx->volume
																							 rate:ctx->rate
																								url:ctx->url
																							 text:ctx->text];
		
	}
	
}

#pragma mark -

#pragma mark Startup / Exit

bool IsProcessOnExit()
{
	C_TEXT name;
	PA_long32 state, time;
	PA_GetProcessInfo(PA_GetCurrentProcessNumber(), name, &state, &time);
	CUTF16String procName(name.getUTF16StringPtr());
	CUTF16String exitProcName((PA_Unichar *)"$\0x\0x\0\0\0");
	return (!procName.compare(exitProcName));
}

void OnExit()
{
	for(std::map<uint32_t, SpeechSynthesizerDelegate*>::iterator i = speech::speech_contexts.begin(); i != speech::speech_contexts.end(); i++)
	{
		SpeechSynthesizerDelegate *speech = i->second;
		[speech abort];
	}
	
	speech::speech_contexts.clear();
}

void OnCloseProcess()
{
	if(IsProcessOnExit())
	{
		speech::isDying = YES;
		
		PA_RunInMainProcess((PA_RunInMainProcessProcPtr)OnExit, NULL);
	}
}

#endif

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
		case kCloseProcess :
			OnCloseProcess();
			break;
			// --- Speech

		case 1 :
			VOICES_LIST(pResult, pParams);
			break;

		case 2 :
			SAY(pResult, pParams);
			break;

	}
}

#pragma mark -

// ------------------------------------ Speech ------------------------------------

void VOICES_LIST(sLONG_PTR *pResult, PackagePtr pParams)
{
	ARRAY_TEXT Param1;
	Param1.fromParamAtIndex(pParams, 1);

#if VERSIONMAC
	NSArray *voices = [NSSpeechSynthesizer availableVoices];
	
	if([voices count])
	{
		Param1.setSize(1);
		for(NSUInteger i = 0; i < [voices count];++i)
			Param1.appendUTF16String((NSString *)[voices objectAtIndex:i]);
	}
#else

#endif
	Param1.toParamAtIndex(pParams, 1);
}

void SAY(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT Param1;
	C_TEXT Param2;
	C_TEXT Param3;

	Param1.fromParamAtIndex(pParams, 1);
	Param2.fromParamAtIndex(pParams, 2);
	Param3.fromParamAtIndex(pParams, 3);

#if VERSIONMAC
		
		say_ctx ctx;
		
		ctx.text = Param1.copyUTF16String();
		ctx.url	= Param3.copyUrl();
		ctx.rate = 180.0f;
		ctx.volume = 0.0f;
		ctx.voice = nil;
		
		CUTF8String u8str;
		Param2.copyUTF8String(&u8str);
		cJSON *json = cJSON_Parse((const char *)u8str.c_str());
		
		if(json)
		{
			cJSON *json_rate = cJSON_GetObjectItem(json, "rate");
			if((json_rate) && cJSON_IsNumber(json_rate))
				ctx.rate = json_rate->valuedouble;
			
			cJSON *json_volume = cJSON_GetObjectItem(json, "volume");
			if((json_volume) && cJSON_IsNumber(json_volume))
				ctx.volume = json_volume->valuedouble;
			
			cJSON *json_voice = cJSON_GetObjectItem(json, "voice");
			if((json_voice) && cJSON_IsString(json_voice))
			{
				ctx.voice = [NSString stringWithUTF8String:(const char *)json_voice->string];
			}
			cJSON_Delete(json);
		}

		PA_RunInMainProcess((PA_RunInMainProcessProcPtr)say, &ctx);
		
		[ctx.text release];
		if(ctx.url) [ctx.url release];
		
#else
		
#endif
	
}
