/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Speech Synthesizer
 #	author : miyako
 #	2017/05/30
 #
 # --------------------------------------------------------------------------------*/

#include "cJSON.h"

#if VERSIONMAC
#include <AppKit/AppKit.h>
#else
#include <sapi.h>
#endif

// --- Speech
void VOICES_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void SAY(sLONG_PTR *pResult, PackagePtr pParams);
